/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {
        colors: {
          "on-error-container": "#742410",
          "on-primary": "#faf7f6",
          "on-surface-variant": "#5a6061",
          "tertiary-fixed": "#f4f3f3",
          "on-secondary-fixed": "#443f34",
          "error-container": "#fe8b70",
          "on-primary-container": "#525151",
          "surface-variant": "#dde4e5",
          "on-error": "#fff7f6",
          "outline": "#757c7d",
          "inverse-on-surface": "#9c9d9d",
          "surface-container-high": "#e4e9ea",
          "on-tertiary-fixed": "#484a4a",
          "surface-bright": "#f9f9f9",
          "secondary-container": "#ebe1d2",
          "surface-container-lowest": "#ffffff",
          "on-tertiary-container": "#5a5c5c",
          "on-tertiary-fixed-variant": "#656667",
          "on-secondary-container": "#575145",
          "secondary-dim": "#585247",
          "primary-dim": "#535252",
          "surface-container-low": "#f2f4f4",
          "tertiary-dim": "#525354",
          "on-secondary": "#fff8ef",
          "on-surface": "#2d3435",
          "surface-tint": "#5f5e5e",
          "surface-container": "#ebeeef",
          "surface": "#f9f9f9",
          "secondary-fixed": "#ebe1d2",
          "on-primary-fixed-variant": "#5c5b5b",
          "tertiary": "#5e5f5f",
          "on-primary-fixed": "#3f3f3f",
          "secondary-fixed-dim": "#dcd3c4",
          "secondary": "#645e52",
          "tertiary-container": "#f4f3f3",
          "tertiary-fixed-dim": "#e5e5e5",
          "primary-container": "#e4e2e1",
          "primary-fixed-dim": "#d6d4d3",
          "inverse-primary": "#ffffff",
          "background": "#f9f9f9",
          "on-secondary-fixed-variant": "#615b4f",
          "surface-dim": "#d4dbdd",
          "primary-fixed": "#e4e2e1",
          "outline-variant": "#adb3b4",
          "on-background": "#2d3435",
          "surface-container-highest": "#dde4e5",
          "error": "#9e422c",
          "on-tertiary": "#f9f9f9",
          "inverse-surface": "#0c0f0f",
          "primary": "#5f5e5e",
          "error-dim": "#5c1202"
        },
        fontFamily: {
          "headline": ["Manrope"],
          "body": ["Manrope"],
          "label": ["Manrope"]
        },
        borderRadius: {
          "DEFAULT": "0.25rem", 
          "lg": "1rem", 
          "xl": "1.5rem", 
          "full": "9999px"
        },
      },
    },
    plugins: [],
}
