<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Resources\CategoryResource;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Laravel\Facades\Image;

class AdminCategoryController extends Controller
{
    /**
     * List all categories (for admin table).
     */
    public function index(Request $request)
    {
        $categories = Category::with(['children'])->withCount('products')
            ->orderBy('name', 'asc')
            ->get();

        return CategoryResource::collection($categories);
    }

    /**
     * Create new category.
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'parent_id' => 'nullable|exists:categories,id',
            'is_active' => 'sometimes|boolean',
            'description' => 'nullable|string',
            'image' => ($request->hasFile('image')) ? 'image|mimes:jpeg,png,webp|max:5120' : 'nullable',
        ]);

        $data = $request->except('image');
        // Slug is auto-generated by EloquentSluggable in Category model
        if ($request->hasFile('image')) {
            $data['image'] = $this->uploadImage($request->file('image'));
        }

        $category = Category::create($data);

        return new CategoryResource($category);
    }

    /**
     * Update category.
     */
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);
        
        $request->validate([
            'name' => 'required|string|max:255',
            'parent_id' => 'nullable|exists:categories,id',
            'is_active' => 'sometimes|boolean',
            'description' => 'nullable|string',
            'image' => ($request->hasFile('image')) ? 'image|mimes:jpeg,png,webp|max:5120' : 'nullable',
        ]);

        $data = $request->except('image');
        if ($request->hasFile('image')) {
            // Delete old
            if ($category->image) {
                Storage::disk('public')->delete(str_replace('/storage/', '', $category->image));
            }
            $data['image'] = $this->uploadImage($request->file('image'));
        }

        $category->update($data);

        return new CategoryResource($category);
    }

    private function uploadImage($imageFile)
    {
        $path = $imageFile->store('categories', 'public');
        
        // Resize to something reasonable for categories, maybe square
        Image::read(Storage::disk('public')->path($path))
            ->cover(400, 400)
            ->save();

        return $path;
    }

    /**
     * Delete category (prevent if has products or children?).
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        
        if ($category->products()->exists() || $category->children()->exists()) {
            return response()->json([
                'message' => 'Cannot delete category that has products or subcategories.'
            ], 422);
        }

        $category->delete();

        return response()->json(['message' => 'Category deleted successfully']);
    }
}
